### ISSUE TITLE
[TS-290] in run-staticcheck step, build fail if we have unmatched go version 

### ISSUE THREAD

**Issue by ghost** [codacy/codacy-analysis-cli-action#109]
I am using go1.18 in my project, and in the previous steps, I have used actions/setup-go@v2 with go-version 1.18. to run codacy analysis CLI, the static-check still give me no option to use go1.20. I saw the shell script change 3 days ago and yesterday there is a fix version. I can live with the update but I need an option inside of staticcheck to set go version.

**Comment by ghost** [comment]
when I update actions/setup-go@v3, it will pass. But this static check still need to based on client pointed go version check and becomes meaningful. 
Attachment of part of my action:

```
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GO111MODULE: on
      GOPRIVATE: github.com/company/*
      GONOSUMDB: github.com/company/*
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup GoLang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18 # The Go version to download (if necessary) and use.

      - name: Configure Git for Golang
        run: |
          git config --global url."https://${{ secrets.CODACY_GH_TOKEN }}:x-oauth-basic@github.com/company".insteadOf "https://github.com/company"

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          run-staticcheck: true
          run-gosec: true
          skip-uncommitted-files-check: true
          allow-network: true
          api-token: ${{ secrets.CODACY_API }}
          upload: true
          max-allowed-issues: 2147483647
```
