### ISSUE TITLE
[CY-4645] "You cannot call a method on a null-valued expression." on "Set up projects for analysis"

### ISSUE THREAD

**Issue by paulomorgado** [codacy/codacy-analysis-cli-action#62]
I'm getting this error on "Set up projects for analysis"

```text
InvalidOperation: D:\a\_temp\238bcc4a-d7dd-49be-9a75-f51f8f0d60ab.ps1:94
Line |
  94 |    $propertyGroups[0].AppendChild($errorLog)
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Error: Process completed with exit code 1.
```
 How can I diagnose this?

**Comment by paulomorgado** [comment]
Looks like a PowerShell script is trying to add a child to a `PropoertyGroup` and something is `$null.`

If you point me to the code, I might be able to figure it out.

**Comment by lolgab** [comment]
Hi @paulomorgado,
Can you share a file with the entire log?

**Comment by paulomorgado** [comment]
Sure! How can I do that?

By the way, the repo is this: https://github.com/paulomorgado/Microsoft.Extensions.AspNet

And here is the securitycodescan-analysis.yml file:

```yaml
# This workflow integrates SecurityCodeScan with GitHub's Code Scanning feature
# SecurityCodeScan is a vulnerability patterns detector for C# and VB.NET

name: SecurityCodeScan

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '31 23 * * 6'

jobs:
  SCS:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1.0.5
      - uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@main
        
      - name: Restore dependencies	
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@main

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
```

It doesn't seem to be codacy. Is it?
