### ISSUE TITLE
[DOCS-380] Running Go client-side tools requires setting up the Go environment

### ISSUE THREAD

**Issue by prcr** [codacy/codacy-analysis-cli-action#78]
Using the client-side Go tools Gosec and staticcheck requires setting up the Go environment beforehand. For example, using the [GitHub action setup-go](https://github.com/actions/setup-go):

```yaml
jobs:
  codacy-analysis-cli:
    name: start
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set-up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13.8
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          run-staticcheck: "true"
          run-gosec: "true"
          upload: true
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
```

The documentation should make this explicit and provide a suggestion to use the GitHub action.

See [this internal thread on Slack](https://codacy.slack.com/archives/CA8A4L1DY/p1652197154756169) for more context.
