### ISSUE TITLE
[CY-6555] Codacy analysis empty Sarif file

### ISSUE THREAD

**Issue by AntonioFalcaoJr** [codacy/codacy-analysis-cli-action#89]
It sounds like the analysis results are empty. Error 422 during upload. What am I missing?

Trying to use: [Integration with GitHub code scanning](https://github.com/codacy/codacy-analysis-cli-action#integration-with-github-code-scanning)

JOB link: https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425

**YAML**

```yaml
on:
  workflow_call:
    inputs:
      path:
        description: 'The path of project passed from the caller workflow'
        required: true
        type: string

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Run Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          directory: ${{ inputs.path }}
          verbose: false
          output: results.sarif
          format: sarif
          tool: sonarscharp
          gh-code-scanning-compat: true
          max-allowed-issues: 10
          fail-if-incomplete: true

      - name: cat results.sarif
        run: cat results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
```

Example of `${{ inputs.path }}`: [src/Services/Account](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/tree/release/src/Services/Account)

**CAT results.sarif**

```log
Run cat results.sarif
  cat results.sarif
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /home/runner/.dotnet
    CODACY_BASE_URL_OR_DEFAULT: https://api.codacy.com
    OWNER_NAME: AntonioFalcaoJr
    REPOSITORY_NAME: EDA.CleanArch.DDD.CQRS.EventSourcing
    ORGANIZATION_PROVIDER: gh
    COMMIT_SHA: 6[2](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:5:2)479c79[3](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:5:3)7ee[4](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:5:4)484c038490[5](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:5:5)8cc9b20[6](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:5:6)0d[7](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:5:7)5aa7d
    CODACY_ANALYSIS_CLI_VERSION: 7.6.4
    CLI_SCRIPT_PATH: /home/runner/work/_actions/codacy/codacy-analysis-cli-action/master/codacy-analysis-cli.sh
{"$schema":"https://docs.oasis-open.org/sarif/sarif/v2.1.0/cos02/schemas/sarif-schema-2.1.0.json","version":"2.1.0","runs":[]}
```
**UploadSarif results**

```log
Run github/codeql-action/upload-sarif@main
  with:
    sarif_file: results.sarif
    checkout_path: /home/runner/work/EDA.CleanArch.DDD.CQRS.EventSourcing/EDA.CleanArch.DDD.CQRS.EventSourcing
    token: ***
    matrix: null
    wait-for-processing: true
  env:
    DOTNET_ROOT: /home/runner/.dotnet
    CODACY_BASE_URL_OR_DEFAULT: https://api.codacy.com
    OWNER_NAME: AntonioFalcaoJr
    REPOSITORY_NAME: EDA.CleanArch.DDD.CQRS.EventSourcing
    ORGANIZATION_PROVIDER: gh
    COMMIT_SHA: 6[2](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:2)479c79[3](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:3)7ee[4](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:4)484c038490[5](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:5)8cc9b20[6](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:6)0d[7](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:7)5aa7d
    CODACY_ANALYSIS_CLI_VERSION: 7.6.4
    CLI_SCRIPT_PATH: /home/runner/work/_actions/codacy/codacy-analysis-cli-action/master/codacy-analysis-cli.sh
Uploading results
  Processing sarif files: ["results.sarif"]
  Uploading results
  Error: Invalid request.
  
  1 item required; only 0 were supplied.
  RequestError [HttpError]: Invalid request.
  
  1 item required; only 0 were supplied.
      at /home/runner/work/_actions/github/codeql-action/main/node_modules/@octokit/request/dist-node/index.js:66:23
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/main/node_modules/bottleneck/light.js:405:1[8](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:8)) {
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '123',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 04 Oct 2022 15:1[9](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:9):41 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '07C3:5317:E784D2:1DC[10](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:10)1B:633C4F0D',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '995',
      'x-ratelimit-reset': '1664896956',
      'x-ratelimit-resource': 'code_scanning_upload',
      'x-ratelimit-used': '5',
      'x-xss-protection': '0'
    },
    request: {
      method: 'PUT',
      url: 'https://api.github.com/repos/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/code-scanning/analysis',
      headers: {
        accept: 'application/vnd.github.v3+json',
        'user-agent': 'CodeQL-Action/2.1.27 octokit-core.js/3.1.2 Node.js/16.13.0 (linux; x64)',
        authorization: 'token [REDACTED]',
        'content-type': 'application/json; charset=utf-8'
      },
      body: '{"commit_oid":"62479c7937ee4484c03849058cc9b2060d75aa7d","ref":"refs/heads/improvment/responsibilities-split","analysis_key":".github/workflows/account.yaml:analyze","analysis_name":"Account","sarif":"H4sIAAAAAAAAA6tWKkstKs7Mz1OyUjLSM9QzUNJRKirNK1ayio6tBQBSlZKzHQAAAA==","workflow_run_id":3183309786,"checkout_uri":"file:///home/runner/work/EDA.CleanArch.DDD.CQRS.EventSourcing/EDA.CleanArch.DDD.CQRS.EventSourcing","environment":"null","started_at":"2022-10-04T15:19:40.[11](https://github.com/AntonioFalcaoJr/EDA.CleanArch.DDD.CQRS.EventSourcing/actions/runs/3183309786/jobs/5190410425#step:6:11)0Z","tool_names":[]}',
      request: { agent: [Agent], hook: [Function: bound bound register] }
    },
    documentation_url: 'https://docs.github.com/rest'
  }
```
